/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "ask1.h"

int *
inner_product_1_svc(XY_array *argp, struct svc_req *rqstp){ //selection 1
	static int  result = 0;

	printf("Function for the inner product has been called...\n");

	int i, j, sum = 0;
	
	for(i=0; i<argp->XY_size/2; i++) {
		result += argp->XY.XY_val[i] * argp->XY.XY_val[argp->XY_size/2+i];
	}
		
	return &result;
}

float * //average callculation
averagex_1_svc(X_array *argp, struct svc_req *rqstp){
	static float  result;

	printf("Average function for array X has been called...\n");
	
	int i;
	float sum=0;
	
	for(i=0; i<argp->X_size; i++){
		sum+=argp->X.X_val[i];
	}
		
	result=sum/argp->X_size;

	return &result;
}

float *
averagey_1_svc(Y_array *argp, struct svc_req *rqstp){
	static float  result;

	printf("Average function for array Y has been called...\n");
	
	int i;
	float sum=0;

	for(i=0;i<argp->Y_size;i++){
		sum+=argp->Y.Y_val[i];	
	}
		
	result=sum/argp->Y_size;

	return &result;
}

rXY *
product_1_svc(r_times_X_Y *argp, struct svc_req *rqstp){
	static rXY  result;

	printf("Function for the r*(X+Y) calculation has been called...\n");

	result.prod.prod_len=argp->X_Y_size;
	result.prod.prod_val=(float *)malloc(argp->X_Y_size*sizeof(float));
	
	int i;
	
	for(i=0;i<argp->X_Y_size;i++)
		result.prod.prod_val[i]=argp->r*argp->X_Y.X_Y_val[i];

	return &result;
}
